import local.pad.uu.touchpad.ScrollState;
import local.pad.uu.touchpad.SwipeState;
import local.pad.uu.touchpad.ScrollOrigins;
import local.pad.uu.touchpad.DragState;
import local.pad.uu.touchpad.RepeatGate;
import local.pad.uu.touchpad.TwoFingerScroll;
import local.pad.uu.touchpad.ScrollMomentum;
import local.pad.uu.touchpad.ThreeFingerMode;
import java.util.ArrayDeque;

/** 验证真实输入边界：增减手指、取消、重复移动和亚单位滚动。 */
public final class InputStateTest {
    private static int checks;
    private static void check(boolean value, String message) {
        checks++;
        if (!value) throw new AssertionError(message);
    }
    private static int move(SwipeState state, int action, int fingers, float x, float y) {
        return state.update(action, fingers, x, y, false, 8);
    }
    public static void main(String[] args) {
        ThreeFingerMode three = new ThreeFingerMode();
        three.begin(10, 10, 40, 1000);
        check(three.move(10.3f, 10, 39.7f, 1020) == ThreeFingerMode.WAIT, "三指落下轻微抖动不选择用途");
        check(three.move(10, 12, 39.6f, 1080) == ThreeFingerMode.NAVIGATE, "三指直接滑动优先导航");
        check(three.move(10, 25, 40, 1500) == ThreeFingerMode.NAVIGATE, "导航途中停留不会误变成拖拽");
        check(three.move(10, 25, 25, 1520) == ThreeFingerMode.NAVIGATE, "已开始导航后收拢不打开启动台");
        three.begin(10, 10, 40, 2000);
        check(three.move(10.2f, 10, 40, 2400) == ThreeFingerMode.WAIT, "单纯停留不点击鼠标");
        check(three.move(10, 12, 39.7f, 2420) == ThreeFingerMode.DRAG, "三指停留后移动进入拖拽");
        check(three.move(20, 20, 40, 2450) == ThreeFingerMode.DRAG, "拖拽中改变方向不触发导航");
        check(three.move(20, 20, 25, 2480) == ThreeFingerMode.DRAG, "已按住鼠标时收拢不抢走拖拽");
        three.begin(10, 10, 40, 3000);
        check(three.move(10, 13, 40, 3100) == ThreeFingerMode.NAVIGATE, "抬手后下一次手势重新选择");
        three.begin(10, 10, 40, 4000);
        check(three.move(10.7f, 10.2f, 38.3f, 4410) == ThreeFingerMode.WAIT, "停留后先改变指距不能开始拖拽");
        check(three.move(14, 10, 30, 4470) == ThreeFingerMode.PINCH, "非对称收拢允许重心移动");
        check(three.move(14, 10, 28, 4480) == ThreeFingerMode.WAIT, "一次收拢只触发一次");
        check(three.move(30, 10, 30, 4500) == ThreeFingerMode.WAIT, "收拢触发后不再导航或拖拽");
        three.begin(10, 10, 40, 5000);
        check(three.move(10.2f, 10, 39.5f, 5010) == ThreeFingerMode.WAIT, "落指时轻微间距变化不触发");
        check(three.move(10.3f, 10, 34, 5040) == ThreeFingerMode.WAIT, "收拢不足时继续等待");
        check(three.move(10.4f, 10, 31, 5080) == ThreeFingerMode.PINCH, "快速对称收拢可触发");
        three.begin(10, 10, 40, 6000);
        check(three.move(10, 10, 45, 6040) == ThreeFingerMode.WAIT, "三指外张不打开启动台");
        check(three.move(10, 10, 25, 6150) == ThreeFingerMode.WAIT, "外张后反向收拢不误触发");
        three.begin(10, 10, 12, 7000);
        check(three.move(10, 10, 9.5f, 7040) == ThreeFingerMode.WAIT, "手指靠得近时仍要求足够实际收拢距离");
        check(three.move(10, 10, 7, 7080) == ThreeFingerMode.PINCH, "较小指距的明确收拢可触发");
        three.begin(10, 10, 40, 8000);
        check(three.move(10, 10, Float.NaN, 8010) == ThreeFingerMode.WAIT, "异常指距不触发动作");
        check(three.move(10, 10, 30, 8050) == ThreeFingerMode.PINCH, "下一次有效收拢正常处理");
        TwoFingerScroll two = new TwoFingerScroll();
        two.begin(100, 100, 200, 100);
        check(two.move(101, 100, 201, 100, 20, 20) == TwoFingerScroll.WAIT, "落指抖动不能吞掉双指轻点");
        check(two.move(108, 100, 208, 100, 20, 20) == TwoFingerScroll.SCROLL, "同向移动无需等待固定时长");
        check(two.dx() == 8 && two.dy() == 0, "滚动保留起步阈值内的位移");
        two.move(112, 96, 212, 96, 20, 20);
        check(two.dx() == 4 && two.dy() == -4, "双轴滚动保持连续增量");
        two.move(110, 94, 210, 94, 20, 20);
        check(two.dx() == -2 && two.dy() == -2, "滚动中反向立即生效");
        two.begin(100, 100, 200, 100);
        check(two.move(90, 100, 210, 100, 20, 20) == TwoFingerScroll.PINCH, "相反方向移动保留捏合");
        check(two.move(120, 100, 220, 100, 20, 20) == TwoFingerScroll.PINCH, "已判定的捏合不会中途变成滚动");
        two.begin(100, 100, 200, 100);
        check(two.move(130, 100, 200, 100, 20, 20) == TwoFingerScroll.PINCH, "一指固定另一指移动仍可缩放");
        two.begin(100, 100, 200, 100);
        check(two.move(100, 92, 200, 92, 20, 20) == TwoFingerScroll.SCROLL, "新手势不继承捏合状态");
        check(two.move(Float.NaN, 92, 200, 92, 20, 20) == TwoFingerScroll.WAIT, "拒绝异常触点");
        ScrollMomentum momentum = new ScrollMomentum();
        momentum.begin(1000);
        check(!momentum.release(1010), "没有位移的轻触无惯性");
        momentum.sample(10, 0, 1020);
        momentum.sample(10, 0, 1040);
        check(momentum.release(1050), "刚移动后抬手产生惯性");
        check(momentum.step(1066) && momentum.dx() > 0 && momentum.dy() == 0, "惯性保持方向和轴");
        float previous = momentum.dx();
        check(momentum.step(1082) && momentum.dx() < previous, "惯性逐帧衰减");
        momentum.stop();
        check(!momentum.step(1098), "新触摸或按键能立即停止惯性");
        momentum.begin(2000); momentum.sample(20, 0, 2020);
        check(!momentum.release(2121), "移动后停留再抬手不惯性滑动");
        momentum.begin(3000); momentum.sample(10, 0, 3020); momentum.release(3030);
        check(!momentum.step(3200), "长时间阻塞后不补发积压滚动");
        momentum.begin(4000); momentum.sample(10000, 0, 4001); momentum.release(4002); momentum.step(4018);
        check(momentum.dx() < 192, "异常速度被限制");
        momentum.begin(5000); momentum.sample(0, -10, 5020); momentum.release(5021);
        int frames = 0;
        for (long t = 5037; momentum.step(t); t += 16) frames++;
        check(frames > 0 && frames <= 94, "惯性有明确的最长时限");
        float[] distances = new float[2];
        int[] durations = new int[2];
        for (int i = 0; i < 2; i++) {
            momentum.begin(6000);
            momentum.sample(i == 0 ? 4 : 16, 0, 6020);
            momentum.release(6021);
            for (long t = 6037; momentum.step(t); t += 16) {
                distances[i] += momentum.dx(); durations[i] += 16;
            }
        }
        check(distances[1] > distances[0] * 3.8f, "四倍抬手速度至少产生约四倍惯性距离");
        check(durations[1] > durations[0], "快滑的惯性持续时间更长");
        momentum.begin(7000); momentum.sample(2, 0, 7020); momentum.release(7021, 4);
        check(Math.abs(momentum.speed() - 0.1) < 0.001, "慢速抬手不受快速惯性增益影响");
        momentum.begin(8000); momentum.sample(20, 0, 8020); momentum.release(8021, 2.5f);
        check(Math.abs(momentum.speed() - 2.5) < 0.001, "快速抬手使用设定的惯性增益");
        RepeatGate repeat = new RepeatGate();
        check(!repeat.claim(9, 67, 1000, 0), "普通按下不改变 UU 原有处理");
        check(repeat.claim(9, 67, 1000, 1), "长按产生的首次重复可以发送");
        check(!repeat.claim(9, 67, 1000, 1), "重复投递不造成双倍删除");
        check(repeat.claim(9, 67, 1000, 2), "后续系统重复逐个发送");
        check(!repeat.claim(9, 67, 1000, 1), "过期重复事件不会再次发送");
        check(repeat.claim(19, 67, 1000, 1), "两条键盘接口的状态分开");
        check(repeat.claim(9, 67, 2000, 1), "新一次长按重新计数");
        repeat.release(9, 67);
        check(repeat.claim(9, 67, 3000, 1), "抬起后释放重复记录");
        check(repeat.claim(9, 19, 4000, 1), "方向键重复按下可发送");
        check(repeat.claim(9, 29, 4000, 1), "同一设备不同按键的重复状态独立");
        repeat.release(9, 19);
        check(!repeat.claim(9, 29, 4000, 1), "松开方向键不会清除仍按住的文字键状态");
        check(repeat.claim(9, 29, 4000, 2), "文字键的下一个系统重复可以发送");
        check(repeat.claimPress(9, 24, 5000, 0), "功能控制的首次按下可以发送");
        check(!repeat.claimPress(9, 24, 5000, 0), "重复投递不能执行两次功能动作");
        check(repeat.claimPress(9, 24, 5000, 1), "音量键的后续真实重复可以执行");
        // 重现嵌套事件入队：消费滚动时，原始输入的线程标记已经撤销。
        ScrollOrigins<Object> origins = new ScrollOrigins<>();
        ThreadLocal<Object> active = new ThreadLocal<>();
        ArrayDeque<Object> queue = new ArrayDeque<>();
        Object pad = new Object(), other = new Object();
        String tagged = new String("相同位移"), untagged = new String("相同位移");
        active.set(pad);
        origins.mark(tagged, active.get());
        queue.add(tagged);
        active.remove();
        check(active.get() == null, "滚动出队时原始线程标记已清空");
        check(origins.take(untagged, pad) == null, "同值的触屏事件不能误认为实体触控板");
        check(origins.take(tagged, other) == null, "错误页面不能抢走来源标记");
        check(origins.take(queue.remove(), pad) == pad, "入队后的来源仍可正确恢复");
        check(origins.take(tagged, pad) == null, "消费后不保留过期来源");
        origins.mark(tagged, pad);
        origins.discard(pad);
        check(origins.take(tagged, pad) == null, "页面退出丢弃待处理事件的来源");
        SwipeState swipe = new SwipeState();
        check(move(swipe, 0, 1, 40, 30) == SwipeState.PASS, "单指移动交还 UU");
        check(move(swipe, 5, 2, 90, 60) == SwipeState.PASS, "双指交还滚动识别器");
        check(move(swipe, 5, 3, 130, 90) == SwipeState.CONSUME, "三指导航候选被接管");
        check(move(swipe, 5, 4, 130, 90) == SwipeState.CONSUME, "第四指落下不能把重心变化当成滑动");
        check(move(swipe, 2, 4, 130, 85) == SwipeState.CONSUME, "短距离不误触");
        check(move(swipe, 2, 4, 130, 79) == SwipeState.UP, "四指上滑");
        check(move(swipe, 2, 4, 130, 50) == SwipeState.CONSUME, "同次手势只触发一次");
        check(move(swipe, 6, 2, 130, 50) == SwipeState.CONSUME, "剩余两指不能继续触发滚动");
        check(move(swipe, 1, 1, 130, 50) == SwipeState.CONSUME, "最后抬起完成被接管手势");
        check(!swipe.captured(), "抬起后释放状态");
        move(swipe, 0, 1, 20, 20);
        move(swipe, 5, 3, 30, 30);
        check(move(swipe, 5, 4, 90, 90) == SwipeState.CONSUME, "第四指落下重建基准");
        check(move(swipe, 2, 4, 90, 91) == SwipeState.CONSUME, "增指不应造成跳跃");
        check(move(swipe, 2, 4, 101, 90) == SwipeState.RIGHT, "四指右滑");
        move(swipe, 3, 4, 101, 90);
        check(!swipe.captured(), "系统取消清空状态");
        move(swipe, 5, 4, 30, 30);
        check(move(swipe, 2, 4, 42, 42) == SwipeState.CONSUME, "对角线暂不决定方向");
        check(move(swipe, 2, 4, 60, 42) == SwipeState.RIGHT, "方向明确后触发");
        swipe.reset();
        move(swipe, 5, 4, 30, 30);
        swipe.update(2, 4, 30, 40, true, 8);
        check(move(swipe, 2, 4, 30, 55) == SwipeState.CONSUME, "中途按修饰键后取消整次快捷操作");
        swipe.reset();
        move(swipe, 5, 4, 30, 30);
        move(swipe, 5, 5, 30, 30);
        check(move(swipe, 2, 3, 30, 70) == SwipeState.CONSUME, "五指混入后取消整次操作");
        check(move(swipe, 0, 1, 30, 30) == SwipeState.PASS, "丢失抬起时新按下仍能恢复");
        check(swipe.update(5, 4, 0, 0, true, 8) == SwipeState.PASS, "带修饰键不接管原始输入");
        swipe.reset();
        move(swipe, 5, 4, 20, 20);
        check(move(swipe, 2, 4, 10, 20) == SwipeState.LEFT, "左滑方向");
        swipe.reset();
        move(swipe, 5, 4, 20, 20);
        check(move(swipe, 2, 4, 20, 31) == SwipeState.DOWN, "下滑方向");
        swipe.reset();
        move(swipe, 5, 3, 20, 20);
        check(move(swipe, 2, 3, 20, 10) == SwipeState.UP, "三指直接上滑恢复导航");
        check(move(swipe, 2, 3, 40, 10) == SwipeState.CONSUME, "三指同次手势不会重复触发");
        swipe.reset();
        move(swipe, 5, 3, 20, 20);
        move(swipe, 6, 2, 20, 20);
        move(swipe, 5, 3, 20, 20);
        check(move(swipe, 2, 3, 20, 40) == SwipeState.CONSUME, "中途少一指再补回不误导航");
        DragState drag = new DragState();
        drag.begin(100, 100, 1000);
        check(drag.move(130, 100, 1020, 20, 20) == DragState.NONE, "给第四指落下保留识别时间");
        check(drag.move(103, 100, 1050, 20, 20) == DragState.NONE, "静止轻触不产生左键单击");
        check(drag.move(125, 100, 1060, 20, 20) == DragState.START, "三指移动开始拖拽");
        check(drag.dx() == 25 && drag.dy() == 0, "首段拖拽保留阈值之前的移动");
        check(drag.move(130, 98, 1070, 20, 20) == DragState.MOVE, "持续拖拽不重复按下左键");
        check(drag.dx() == 5 && drag.dy() == -2, "增量位移保持方向");
        check(drag.move(130, 98, 1080, 20, 20) == DragState.NONE, "静止不重复发移动");
        drag.reset();
        drag.begin(500, 500, 2000);
        check(drag.move(502, 500, 2050, 20, 20) == DragState.NONE, "新一次落指重新计算阈值");
        ScrollState scroll = new ScrollState();
        int total = 0;
        for (int i = 0; i < 100; i++) total += scroll.convert(0, 0.4f, -0.25f);
        check(total == -10, "慢速微小移动累计保留且方向翻转");
        scroll.reset();
        check(scroll.convert(0, 2, 0.25f) == 0, "水平余量尚未达到单位");
        check(scroll.convert(1, 4, 0.25f) == 1, "两轴余量互不干扰");
        check(scroll.convert(0, 2, 0.25f) == 1, "水平余量保留");
        scroll.reset();
        scroll.convert(0, 3, 0.25f);
        check(scroll.convert(0, -4, 0.25f) == -1, "反向立即响应，不被旧余量阻滞");
        check(scroll.convert(0, Float.NaN, 1) == 0, "拒绝非数值输入");
        check(scroll.convert(0, Float.POSITIVE_INFINITY, 1) == 0, "拒绝无限输入");
        check(scroll.convert(0, 100000, 1) == 960, "异常大位移有界");
        check(scroll.convert(0, 0, 1) == 0, "被限制的位移不留积压");
        System.out.println("通过 " + checks + " 项输入边界检查");
    }
}
