import Foundation

func frame(_ text: String) -> InputFrame { InputFrame.decode(Data(text.utf8))! }
let hello = frame(#"{"v":1,"t":"hello","at":1,"seq":1,"epoch":0,"mods":0}"#)
let position = frame(#"{"v":1,"t":"position","at":2,"seq":2,"epoch":1,"mods":0,"x":2,"y":3,"w":2880,"h":1800,"local":true}"#)
var gate = PadGate()
precondition(gate.accept(position, epoch: 1, ready: true, now: 0) == .rejected)
precondition(gate.accept(hello, epoch: 1, ready: true, now: 0) == .hello)
precondition(gate.accept(hello, epoch: 1, ready: true, now: 0.1) == .rejected)
precondition(gate.accept(position, epoch: 1, ready: true, now: 0.2) == .event)
let oldScreen = frame(#"{"v":1,"t":"position","at":3,"seq":3,"epoch":1,"mods":0,"x":2,"y":3,"w":2880,"h":1800,"local":true}"#)
precondition(gate.accept(oldScreen, epoch: 2, ready: true, now: 0.3) == .rejected)
let reset = frame(#"{"v":1,"t":"reset","at":4,"seq":4,"epoch":1}"#)
precondition(gate.accept(reset, epoch: 2, ready: false, now: 0.4) == .reset)
precondition(!gate.active)
let resume = frame(#"{"v":1,"t":"hello","at":5,"seq":5,"epoch":2,"mods":0}"#)
precondition(gate.accept(resume, epoch: 2, ready: false, now: 1) == .hello)
precondition(!gate.expire(now: 5) && gate.expire(now: 5.01) && !gate.active)
let staleSync = frame(#"{"v":1,"t":"sync","at":6,"seq":6,"epoch":2,"mods":0}"#)
precondition(gate.accept(staleSync, epoch: 2, ready: true, now: 6) == .rejected)
precondition(gate.accept(frame(#"{"v":1,"t":"hello","at":7,"seq":7,"mods":0}"#), epoch: 2, ready: false, now: 7) == .hello)
precondition(gate.accept(frame(#"{"v":1,"t":"action","at":8,"seq":8,"epoch":2,"a":"volume-up"}"#), epoch: 2, ready: false, now: 8) == .rejected)
precondition(InputFrame.decode(Data(#"{"v":1,"t":"action","at":1,"seq":9,"a":"run-shell"}"#.utf8)) == nil)
precondition(InputFrame.decode(Data(#"{"v":1,"t":"button","at":1,"seq":9,"button":4,"down":true,"mods":0}"#.utf8)) == nil)
precondition(InputFrame.decode(Data(#"{"v":1,"t":"position","at":1,"seq":9,"x":-1,"y":0,"w":2,"h":2,"local":true,"mods":0}"#.utf8)) == nil)
print("握手、顺序、重复帧、显示代次、超时释放与非法动作检查通过；没有发送输入。")
